### ISSUE TITLE
'npm run dev' doesn't work for the 'no-pwa' branch

### ISSUE THREAD

**Issue by MartinRL** [erisu/pwa-vue-app-1#6]
Was following your tutorial at Medium (https://medium.com/the-web-tub/creating-your-first-vue-js-pwa-project-22f7c552fb34) but couldn't get 'npm run dev' to work (where the reader reaches the end of branch 'no-pwa'). Forking 'no-pwa' also yield: 

 webpack-dev-server --progress

10% building 1/1 modules 0 activeevents.js:186
      throw er; // Unhandled 'error' event
      ^
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwa-vue-app-1@1.0.0 dev: `webpack-dev-server --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwa-vue-app-1@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by erisu** [comment]
Sorry for not noticing this issue earlier.

The error message `EADDRINUSE` means some process is already running on the address `127.0.0.1:9000`.

The only option in this type of case is to find out what process you are running on port `9000` and terminate it so this process to run or change the port number to something that is available.

For the `no-pwa` branch, the port number can be changed here: 

https://github.com/erisu/pwa-vue-app-1/blob/4ba3b33ad6faf0bb6709be9ec73e0d648f4ab0d1/webpack.config.js#L111
